version: '3.8'

services:
  postgres:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev
      - PGADMIN_DEFAULT_PASSWORD=dev
    volumes:
      - vol-pgadmin:/root/.pgadmin

volumes:
  vol-pgadmin: